import crypto from 'crypto';
import fs from 'fs';
import os from 'os';
import path from 'path';

import express from 'express';
import multer from 'multer';

import { userDb, auditLogDb, invitesDb } from '../modules/database/index.js';
import { generateToken, authenticateToken, requireRole } from '../middleware/auth.js';
import { createRateLimiter } from '../middleware/rate-limit.js';
import { verifyPassword, needsRehash, hashPassword } from '../services/password.service.js';
import { createInvite, acceptInvite, InviteError } from '../services/invite.service.js';
import { clientIp } from '../utils/client-ip.js';

import webauthnRouter from './webauthn.js';

const MIN_PASSWORD_LENGTH = 8;
const USERNAME_PATTERN = /^[a-zA-Z0-9_]{3,32}$/;

// Avatar upload (PATCH /me/avatar). Files live under ~/.nassaj-users/<userId>/.
const AVATARS_ROOT = path.join(os.homedir(), '.nassaj-users');
const AVATAR_MAX_BYTES = 2 * 1024 * 1024; // 2 MB

// Allowed image MIME types → canonical file extension used on disk and in URL.
const AVATAR_MIME_TO_EXT = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'image/gif': 'gif',
};

// Allowed colour-choice ids for the lettered avatar (kept in sync with the
// client palette in src/components/participants/avatarChoice.ts). The stored
// value is the sentinel `color:<id>`, interpreted by the avatar renderer.
const AVATAR_COLOR_IDS = new Set([
  'rose',
  'orange',
  'amber',
  'emerald',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'fuchsia',
  'pink',
]);

// Curated gallery avatars are static SVGs generated by
// scripts/generate-avatars.mjs into public/avatars-gallery/ and stored as the
// path `/avatars-gallery/<file>`. Strict whitelist of known filenames — never
// a free-form path — so no traversal or arbitrary-URL storage is possible.
// KEEP IN SYNC with src/components/participants/avatarChoice.ts and the
// generator script (which prints this list).
const AVATAR_GALLERY_PATH_PREFIX = '/avatars-gallery/';
const AVATAR_GALLERY_FILES = new Set([
  'lorelei-faris.svg',
  'lorelei-sami.svg',
  'lorelei-yusuf.svg',
  'lorelei-ziyad.svg',
  'notionists-lina.svg',
  'notionists-zaid.svg',
  'notionists-dana.svg',
  'notionists-rami.svg',
  'openpeeps-maya.svg',
  'openpeeps-rami.svg',
  'thumbs-aisha.svg',
  'thumbs-hamza.svg',
]);

// Legacy gallery form (first iteration): self-contained SVG data URIs. No
// longer offered by the picker but still accepted so stale clients keep
// working; svg+xml flavour only, length-capped against blob stuffing.
const AVATAR_GALLERY_LEGACY_PREFIX = 'data:image/svg+xml,';
const AVATAR_GALLERY_MAX_LENGTH = 4096;

// In-memory storage so the buffer is validated before any disk write; the
// filename is derived from the (trusted, numeric) userId, never from client
// input, which removes path-traversal risk on the upload side.
const avatarUpload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: AVATAR_MAX_BYTES, files: 1 },
  fileFilter: (req, file, cb) => {
    if (AVATAR_MIME_TO_EXT[file.mimetype]) {
      return cb(null, true);
    }
    cb(null, false);
  },
}).single('avatar');

const router = express.Router();

// Passkey (WebAuthn) registration, credential management, and login (B-PK).
router.use('/webauthn', webauthnRouter);

// Brute-force protection on credential-checking endpoints (m-RATELIMIT):
// 10 attempts / 15 min / IP on login and invite acceptance.
const authLimiter = createRateLimiter({
  windowMs: 15 * 60_000,
  max: 10,
  message: 'Too many attempts, please try again later',
});

// ---------------------------------------------------------------------------
// Public status
// ---------------------------------------------------------------------------

// Check auth status. needsSetup is true only until the bootstrap owner exists.
router.get('/status', async (req, res) => {
  try {
    const hasUsers = await userDb.hasUsers();
    res.json({ needsSetup: !hasUsers, isAuthenticated: false });
  } catch (error) {
    console.error('Auth status error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ---------------------------------------------------------------------------
// Login (public, rate-limited)
// ---------------------------------------------------------------------------

router.post('/login', authLimiter, async (req, res) => {
  try {
    const { username, password } = req.body ?? {};

    if (!username || !password || typeof username !== 'string' || typeof password !== 'string') {
      return res.status(400).json({ error: 'Username and password are required' });
    }

    const ip = clientIp(req);
    const userAgent = req.headers['user-agent'] ?? null;

    const user = userDb.getUserByUsername(username);
    // Always run a verification path; generic error to avoid user enumeration.
    if (!user) {
      auditLogDb.record('login_failure', {
        metadata: { reason: 'unknown_user' },
        ipAddress: ip,
        userAgent,
      });
      return res.status(401).json({ error: 'Invalid username or password' });
    }

    const isValid = await verifyPassword(user.password_hash, password);
    if (!isValid) {
      auditLogDb.record('login_failure', {
        userId: user.id,
        metadata: { reason: 'bad_password' },
        ipAddress: ip,
        userAgent,
      });
      return res.status(401).json({ error: 'Invalid username or password' });
    }

    // Transparent upgrade of legacy bcrypt hashes to argon2id on login.
    if (needsRehash(user.password_hash)) {
      try {
        const newHash = await hashPassword(password);
        userDb.setPasswordHash(user.id, newHash);
      } catch (err) {
        console.error('Password rehash failed', { error: err?.message });
      }
    }

    const token = generateToken(user);
    userDb.updateLastLogin(user.id);
    auditLogDb.record('login_success', { userId: user.id, ipAddress: ip, userAgent });

    res.json({
      success: true,
      user: { id: user.id, username: user.username, role: user.role },
      token,
    });
  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ---------------------------------------------------------------------------
// Token refresh (issues a fresh JWT for an authenticated user)
// ---------------------------------------------------------------------------

router.post('/refresh', authenticateToken, (req, res) => {
  const token = generateToken(req.user);
  auditLogDb.record('token_refresh', {
    userId: req.user.id,
    ipAddress: clientIp(req),
    userAgent: req.headers['user-agent'] ?? null,
    metadata: { via: 'endpoint' },
  });
  res.json({ success: true, token });
});

// ---------------------------------------------------------------------------
// Current user / logout
// ---------------------------------------------------------------------------

router.get('/user', authenticateToken, (req, res) => {
  // Map the DB row to the client contract: the row stores snake_case
  // (avatar_url, must_change_password) but the frontend AuthUser type expects
  // camelCase. Returning the raw row left user.avatarUrl undefined, so the
  // sidebar/header avatar fell back to the initial after an upload.
  const { id, username, role, status, avatar_url, mustChangePassword } = req.user;
  res.json({
    user: {
      id,
      username,
      role,
      status,
      avatarUrl: avatar_url ?? null,
      mustChangePassword: Boolean(mustChangePassword),
    },
  });
});

// Current user (C-AUTH-4) — minimal identity for the client. req.user is the
// public row (id, username, role, status, avatar_url) loaded by authenticateToken.
router.get('/me', authenticateToken, (req, res) => {
  const { id, username, role, status, avatar_url } = req.user;
  res.json({ id, username, role, status, avatarUrl: avatar_url ?? null });
});

router.post('/logout', authenticateToken, (req, res) => {
  // Behind authenticateToken, so req.user is guaranteed. Record the explicit
  // logout for the auth timeline (T-182). Best-effort: never blocks the response.
  auditLogDb.record('logout', {
    userId: req.user.id,
    ipAddress: clientIp(req),
    userAgent: req.headers['user-agent'] ?? null,
  });
  res.json({ success: true, message: 'Logged out successfully' });
});

// ---------------------------------------------------------------------------
// Invite flow (C-AUTH-4)
// ---------------------------------------------------------------------------

// Accept an invite → creates a `user` account (public, rate-limited).
router.post('/invite/accept', authLimiter, async (req, res) => {
  try {
    const { token, username, password } = req.body ?? {};
    const user = await acceptInvite({ token, username, password }, clientIp(req));
    const jwtToken = generateToken(user);
    res.json({
      success: true,
      user: { id: user.id, username: user.username, role: user.role },
      token: jwtToken,
    });
  } catch (error) {
    if (error instanceof InviteError) {
      return res.status(error.status).json({ error: error.message });
    }
    console.error('Invite accept error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Create an invite (owner/admin only). Returns the plaintext token ONCE.
router.post('/invites', authenticateToken, requireRole('owner', 'admin'), async (req, res) => {
  try {
    const { role, email, ttlHours } = req.body ?? {};
    const result = await createInvite(req.user, { role, email, ttlHours });
    res.status(201).json({ success: true, invite: result });
  } catch (error) {
    if (error instanceof InviteError) {
      return res.status(error.status).json({ error: error.message });
    }
    console.error('Invite create error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// List invites (owner/admin only). Token hashes are never exposed.
router.get('/invites', authenticateToken, requireRole('owner', 'admin'), (req, res) => {
  res.json({ invites: invitesDb.list() });
});

// Revoke a pending invite (owner/admin only).
router.delete('/invites/:id', authenticateToken, requireRole('owner', 'admin'), (req, res) => {
  const id = Number(req.params.id);
  if (!Number.isInteger(id) || id <= 0) {
    return res.status(400).json({ error: 'Invalid invite id' });
  }
  const revoked = invitesDb.revoke(id);
  if (!revoked) {
    return res.status(404).json({ error: 'Invite not found or not pending' });
  }
  auditLogDb.record('invite_revoked', { userId: req.user.id, metadata: { inviteId: id } });
  res.json({ success: true });
});

// ---------------------------------------------------------------------------
// User management (owner/admin only) — minimal listing for RBAC UI later
// ---------------------------------------------------------------------------

router.get('/users', authenticateToken, requireRole('owner', 'admin'), (req, res) => {
  res.json({ users: userDb.listUsers() });
});

const ASSIGNABLE_ROLES = new Set(['owner', 'admin', 'user']);
const VALID_STATUSES = new Set(['active', 'disabled']);

// Change a user's role (owner only). An owner may not demote themselves, and the
// last remaining owner may not be demoted (avoids locking out administration).
router.patch('/users/:id/role', authenticateToken, requireRole('owner'), (req, res) => {
  const id = Number(req.params.id);
  const { role } = req.body ?? {};

  if (!Number.isInteger(id) || id <= 0) {
    return res.status(400).json({ error: 'Invalid user id' });
  }
  if (!role || !ASSIGNABLE_ROLES.has(role)) {
    return res.status(400).json({ error: 'Invalid role' });
  }
  if (id === req.user.id) {
    return res.status(400).json({ error: 'You cannot change your own role' });
  }

  const target = userDb.getRawById(id);
  if (!target) {
    return res.status(404).json({ error: 'User not found' });
  }
  // Guard the last owner: demoting the only remaining owner is forbidden.
  if (target.role === 'owner' && role !== 'owner' && userDb.getOwnerCount() <= 1) {
    return res.status(400).json({ error: 'Cannot demote the last owner' });
  }
  if (target.role === role) {
    return res.json({ success: true });
  }

  userDb.setRole(id, role);
  auditLogDb.record('role_changed', {
    userId: req.user.id,
    metadata: { targetUserId: id, from: target.role, to: role },
    ipAddress: clientIp(req),
  });
  res.json({ success: true });
});

// Suspend / re-activate a user (owner only). Owners may not disable themselves,
// and the last active owner cannot be disabled.
router.patch('/users/:id/status', authenticateToken, requireRole('owner'), (req, res) => {
  const id = Number(req.params.id);
  const { status } = req.body ?? {};

  if (!Number.isInteger(id) || id <= 0) {
    return res.status(400).json({ error: 'Invalid user id' });
  }
  if (!status || !VALID_STATUSES.has(status)) {
    return res.status(400).json({ error: 'Invalid status' });
  }
  if (id === req.user.id) {
    return res.status(400).json({ error: 'You cannot change your own status' });
  }

  const target = userDb.getRawById(id);
  if (!target) {
    return res.status(404).json({ error: 'User not found' });
  }
  if (target.role === 'owner' && status === 'disabled' && userDb.getOwnerCount() <= 1) {
    return res.status(400).json({ error: 'Cannot disable the last owner' });
  }
  if (target.status === status) {
    return res.json({ success: true });
  }

  userDb.setStatus(id, status);
  auditLogDb.record(status === 'disabled' ? 'user_disabled' : 'user_enabled', {
    userId: req.user.id,
    metadata: { targetUserId: id },
    ipAddress: clientIp(req),
  });
  res.json({ success: true });
});

// Permanently delete a user (owner only) [T-116]. Owners may not delete
// themselves, and the last remaining owner cannot be deleted. Removes the DB
// row plus all referencing rows (transactional, see userDb.deleteUser) and the
// per-user sidecar directory (~/.nassaj-users/<id>: avatar + isolated provider
// credentials). Existing JWTs die naturally: authenticateToken can no longer
// resolve the deleted id.
//
//   curl -X DELETE -H "Authorization: Bearer <owner-jwt>" \
//        https://nassaj.alkindy.tech/api/auth/users/7
router.delete('/users/:id', authenticateToken, requireRole('owner'), async (req, res) => {
  try {
    const id = Number(req.params.id);

    if (!Number.isInteger(id) || id <= 0) {
      return res.status(400).json({ error: 'Invalid user id' });
    }
    if (id === req.user.id) {
      return res.status(400).json({ error: 'You cannot delete your own account' });
    }

    const target = userDb.getRawById(id);
    if (!target) {
      return res.status(404).json({ error: 'User not found' });
    }
    if (target.role === 'owner' && userDb.getOwnerCount() <= 1) {
      return res.status(400).json({ error: 'Cannot delete the last owner' });
    }

    const deleted = userDb.deleteUser(id);
    if (!deleted) {
      return res.status(404).json({ error: 'User not found' });
    }

    // Sidecar cleanup (best-effort, non-fatal): the per-user directory holds
    // the uploaded avatar and the isolated provider credential dirs. `id` is a
    // validated positive integer, never raw client input.
    try {
      await fs.promises.rm(path.join(AVATARS_ROOT, String(id)), {
        recursive: true,
        force: true,
      });
    } catch (cleanupError) {
      console.error('User sidecar cleanup failed:', cleanupError?.message);
    }

    auditLogDb.record('user_deleted', {
      userId: req.user.id,
      metadata: { targetUserId: id, targetUsername: target.username, targetRole: target.role },
      ipAddress: clientIp(req),
    });

    res.json({ success: true });
  } catch (error) {
    console.error('User delete error:', error?.message);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ---------------------------------------------------------------------------
// Self-service account management (C-3)
// ---------------------------------------------------------------------------

// Change own password. Rate-limited (verifies a credential). On success the
// current device's token is rotated and returned so it keeps working; all other
// tokens are invalidated via the advanced password_changed_at.
router.patch('/me/password', authenticateToken, authLimiter, async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body ?? {};

    if (
      typeof currentPassword !== 'string' ||
      typeof newPassword !== 'string' ||
      !currentPassword ||
      !newPassword
    ) {
      return res.status(400).json({ error: 'Current and new password are required' });
    }
    if (newPassword.length < MIN_PASSWORD_LENGTH) {
      return res
        .status(400)
        .json({ error: `Password must be at least ${MIN_PASSWORD_LENGTH} characters` });
    }

    // req.user is the public row (no hash); load the full row to verify.
    const fullUser = userDb.getRawById(req.user.id);
    if (!fullUser) {
      return res.status(404).json({ error: 'User not found' });
    }

    const isValid = await verifyPassword(fullUser.password_hash, currentPassword);
    if (!isValid) {
      auditLogDb.record('login_failure', {
        userId: req.user.id,
        metadata: { reason: 'bad_current_password', context: 'password_change' },
        ipAddress: clientIp(req),
        userAgent: req.headers['user-agent'] ?? null,
      });
      return res.status(401).json({ error: 'Current password is incorrect' });
    }

    const changedAt = Date.now();
    const newHash = await hashPassword(newPassword);
    userDb.changePassword(req.user.id, newHash, changedAt);

    // Issue a fresh token carrying the new pwd_iat so this device stays signed in.
    const refreshedUser = userDb.getUserById(req.user.id);
    const token = generateToken(refreshedUser);

    auditLogDb.record('password_changed', {
      userId: req.user.id,
      ipAddress: clientIp(req),
    });

    res.json({ success: true, token });
  } catch (error) {
    console.error('Password change error:', error?.message);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Change own username.
router.patch('/me/username', authenticateToken, (req, res) => {
  try {
    const { username } = req.body ?? {};

    if (typeof username !== 'string' || !USERNAME_PATTERN.test(username)) {
      return res.status(400).json({
        error: 'Username must be 3-32 characters: letters, numbers, or underscore',
      });
    }

    if (username === req.user.username) {
      return res.json({ success: true });
    }

    const existing = userDb.getUserByUsername(username);
    if (existing && existing.id !== req.user.id) {
      return res.status(409).json({ error: 'Username already taken' });
    }

    userDb.setUsername(req.user.id, username);
    auditLogDb.record('username_changed', {
      userId: req.user.id,
      metadata: { from: req.user.username, to: username },
      ipAddress: clientIp(req),
    });

    res.json({ success: true, username });
  } catch (error) {
    console.error('Username change error:', error?.message);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Upload / replace own avatar. Accepts multipart/form-data with field `avatar`
// (jpeg/png/webp/gif, max 2 MB). The image is written to
// ~/.nassaj-users/<userId>/avatar.<ext> (overwriting any prior avatar) and the
// server-relative URL /avatars/<userId>.<ext> is persisted on the user row.
router.patch('/me/avatar', authenticateToken, (req, res) => {
  avatarUpload(req, res, async (uploadError) => {
    try {
      if (uploadError) {
        if (uploadError instanceof multer.MulterError && uploadError.code === 'LIMIT_FILE_SIZE') {
          return res.status(413).json({ error: 'Image exceeds the 2MB size limit' });
        }
        console.error('Avatar upload error:', uploadError?.message);
        return res.status(400).json({ error: 'Invalid upload' });
      }

      const file = req.file;
      if (!file) {
        // Missing field or rejected by fileFilter (unsupported type).
        return res
          .status(400)
          .json({ error: 'A valid image file (jpeg, png, webp, gif) is required' });
      }

      const ext = AVATAR_MIME_TO_EXT[file.mimetype];
      if (!ext) {
        return res.status(400).json({ error: 'Unsupported image type' });
      }

      // userId comes from the verified JWT (numeric), never from client input.
      const userId = req.user.id;

      // Remove any avatar in a different extension so a stale file is not left
      // shadowing the new one (and not served by the static handler).
      const userDir = path.join(AVATARS_ROOT, String(userId));
      await fs.promises.mkdir(userDir, { recursive: true });
      for (const otherExt of Object.values(AVATAR_MIME_TO_EXT)) {
        if (otherExt === ext) {
          continue;
        }
        await fs.promises.rm(path.join(userDir, `avatar.${otherExt}`), { force: true });
      }

      const targetPath = path.join(userDir, `avatar.${ext}`);
      await fs.promises.writeFile(targetPath, file.buffer);

      const avatarUrl = `/avatars/${userId}.${ext}`;
      userDb.setAvatarUrl(userId, avatarUrl);

      auditLogDb.record('avatar_updated', {
        userId,
        metadata: { ext, size: file.size },
        ipAddress: clientIp(req),
      });

      res.json({ success: true, avatarUrl });
    } catch (error) {
      console.error('Avatar update error:', error?.message);
      res.status(500).json({ error: 'Internal server error' });
    }
  });
});

// Pick a curated gallery avatar or a palette colour for the lettered avatar
// (C-MU-UX-AVATAR-PICK / C-MU-UX-AVATAR-PRO). Accepts JSON with exactly one of:
//   { color: "<paletteId>" }                  -> persists `color:<id>`
//   { avatar: "/avatars-gallery/<file>.svg" } -> persists the whitelisted path
//   { avatar: "data:image/svg+xml,…" }        -> legacy first-iteration form
// Unlike /me/avatar this writes no file to disk; both forms live entirely in
// the avatar_url string, so they propagate to every avatar surface unchanged.
router.patch('/me/avatar-choice', authenticateToken, (req, res) => {
  try {
    const body = req.body ?? {};
    const { color, avatar } = body;
    const userId = req.user.id;

    let avatarUrl;
    if (typeof color === 'string') {
      if (!AVATAR_COLOR_IDS.has(color)) {
        return res.status(400).json({ error: 'Unknown avatar colour' });
      }
      avatarUrl = `color:${color}`;
    } else if (typeof avatar === 'string') {
      if (avatar.startsWith(AVATAR_GALLERY_PATH_PREFIX)) {
        // Whitelist match on the exact remaining filename — rejects nested
        // paths, query strings, traversal, and unknown files in one check.
        const file = avatar.slice(AVATAR_GALLERY_PATH_PREFIX.length);
        if (!AVATAR_GALLERY_FILES.has(file)) {
          return res.status(400).json({ error: 'Invalid gallery avatar' });
        }
      } else if (
        !avatar.startsWith(AVATAR_GALLERY_LEGACY_PREFIX) ||
        avatar.length > AVATAR_GALLERY_MAX_LENGTH
      ) {
        return res.status(400).json({ error: 'Invalid gallery avatar' });
      }
      avatarUrl = avatar;
    } else {
      return res.status(400).json({ error: 'A colour or gallery avatar is required' });
    }

    // Any prior uploaded image file is now orphaned; remove it so it does not
    // linger on disk (best-effort, non-fatal).
    void removeAvatarFiles(userId);

    userDb.setAvatarUrl(userId, avatarUrl);

    auditLogDb.record('avatar_updated', {
      userId,
      metadata: { kind: typeof color === 'string' ? 'color' : 'gallery' },
      ipAddress: clientIp(req),
    });

    res.json({ success: true, avatarUrl });
  } catch (error) {
    console.error('Avatar choice error:', error?.message);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Removes any uploaded avatar files for a user (all extensions). Best-effort.
async function removeAvatarFiles(userId) {
  const userDir = path.join(AVATARS_ROOT, String(userId));
  await Promise.all(
    Object.values(AVATAR_MIME_TO_EXT).map((ext) =>
      fs.promises.rm(path.join(userDir, `avatar.${ext}`), { force: true }).catch(() => {}),
    ),
  );
}

// ---------------------------------------------------------------------------
// Admin password reset (C-4) — owner/admin only
// ---------------------------------------------------------------------------

// Reset another user's password to a generated temporary one, returned ONCE in
// plaintext. The target must change it on next use (must_change_password = 1),
// and all of the target's existing tokens are invalidated.
router.post(
  '/users/:id/reset-password',
  authenticateToken,
  requireRole('owner', 'admin'),
  async (req, res) => {
    try {
      const id = Number(req.params.id);
      if (!Number.isInteger(id) || id <= 0) {
        return res.status(400).json({ error: 'Invalid user id' });
      }

      // Self-reset must go through /me/password (preserves current-session token).
      if (id === req.user.id) {
        return res.status(400).json({ error: 'Use /me/password to change your own password' });
      }

      const target = userDb.getRawById(id);
      if (!target) {
        return res.status(404).json({ error: 'User not found' });
      }

      // Only an owner may reset another owner's password.
      if (target.role === 'owner' && req.user.role !== 'owner') {
        return res.status(403).json({ error: 'Insufficient permissions' });
      }

      // 12 random bytes → 16-char base64url temporary password (CSPRNG).
      const tempPassword = crypto.randomBytes(12).toString('base64url');
      const tempHash = await hashPassword(tempPassword);
      userDb.resetPassword(id, tempHash, Date.now());

      // Never log the temporary password.
      auditLogDb.record('password_reset', {
        userId: req.user.id,
        metadata: { targetUserId: id },
        ipAddress: clientIp(req),
      });

      res.json({ tempPassword });
    } catch (error) {
      console.error('Password reset error:', error?.message);
      res.status(500).json({ error: 'Internal server error' });
    }
  }
);

export default router;
