/**
 * Avatar identity choices (C-MU-UX-AVATAR-PICK / C-MU-UX-AVATAR-PRO).
 *
 * The `users.avatar_url` column is a single free-text string that already
 * propagates to every avatar surface (sidebar, presence, messages) via the
 * participant/presence queries. To avoid a schema change we overload that one
 * field to carry three kinds of identity, distinguished by their prefix:
 *
 *   1. `/avatars/<id>.<ext>` or `http(s)://…`  — uploaded image (existing).
 *   2. `/avatars-gallery/<name>.svg`           — a curated gallery avatar
 *      (static DiceBear SVG generated by scripts/generate-avatars.mjs; the
 *      legacy `data:image/svg+xml,…` form from the first gallery iteration
 *      still renders and validates for users who picked one before).
 *   3. `color:<paletteId>`                     — a chosen colour for the
 *                                                lettered (initial) avatar.
 *
 * Forms 1 and 2 are valid image URLs and render through the existing `<img>`
 * path unchanged. Form 3 is a sentinel that `ParticipantAvatar` interprets to
 * paint a specific palette colour behind the username initial instead of the
 * deterministic userId-derived colour.
 *
 * Everything here is pure (no React) so it can be shared by the display
 * component and the profile picker, and is safe to mirror on the server for
 * validation.
 */

export const AVATAR_COLOR_PREFIX = 'color:';

/**
 * Curated palette for the colour picker: a Tailwind background class per id
 * (for the lettered avatar), chosen for >= 4.5:1 contrast against white text.
 */
export const AVATAR_COLORS = [
  { id: 'rose', className: 'bg-rose-500' },
  { id: 'orange', className: 'bg-orange-500' },
  { id: 'amber', className: 'bg-amber-600' },
  { id: 'emerald', className: 'bg-emerald-600' },
  { id: 'teal', className: 'bg-teal-600' },
  { id: 'cyan', className: 'bg-cyan-600' },
  { id: 'sky', className: 'bg-sky-600' },
  { id: 'blue', className: 'bg-blue-600' },
  { id: 'indigo', className: 'bg-indigo-600' },
  { id: 'violet', className: 'bg-violet-600' },
  { id: 'fuchsia', className: 'bg-fuchsia-600' },
  { id: 'pink', className: 'bg-pink-600' },
] as const;

export type AvatarColorId = (typeof AVATAR_COLORS)[number]['id'];

const COLOR_BY_ID = new Map<string, (typeof AVATAR_COLORS)[number]>(
  AVATAR_COLORS.map((c) => [c.id, c]),
);

/** Builds the sentinel value stored in `avatar_url` for a colour choice. */
export function avatarColorValue(id: AvatarColorId): string {
  return `${AVATAR_COLOR_PREFIX}${id}`;
}

/**
 * If `avatarUrl` encodes a colour choice, returns its Tailwind background
 * class; otherwise null. Used by the display component to decide whether to
 * paint a chosen colour rather than the deterministic one.
 */
export function colorClassFromAvatarUrl(avatarUrl: string | null | undefined): string | null {
  if (!avatarUrl || !avatarUrl.startsWith(AVATAR_COLOR_PREFIX)) {
    return null;
  }
  const id = avatarUrl.slice(AVATAR_COLOR_PREFIX.length);
  return COLOR_BY_ID.get(id)?.className ?? null;
}

/** True when the stored value is one of our colour sentinels (not an image). */
export function isAvatarColorValue(avatarUrl: string | null | undefined): boolean {
  return typeof avatarUrl === 'string' && colorClassFromAvatarUrl(avatarUrl) !== null;
}

// ---------------------------------------------------------------------------
// Curated gallery avatars (C-MU-UX-AVATAR-PRO)
// ---------------------------------------------------------------------------

/**
 * Static, professionally illustrated avatars generated at build time from
 * DiceBear styles (all CC0 1.0) by `scripts/generate-avatars.mjs` into
 * `public/avatars-gallery/`. No runtime generation and no external requests —
 * the stored value is just the path, served like any other static asset.
 *
 * KEEP IN SYNC with the whitelist in `server/routes/auth.js`
 * (AVATAR_GALLERY_FILES) and the entry list in the generator script.
 */
export const AVATAR_GALLERY_PATH_PREFIX = '/avatars-gallery/';

export type GalleryAvatar = {
  /** Stable id (the filename stem); used for React keys / selection state. */
  id: string;
  /** The static path to store in avatar_url and render as an <img>. */
  url: string;
};

const GALLERY_IDS = [
  // Lorelei — expressive ink-style portraits (Lisa Wischofsky, CC0 1.0).
  'lorelei-faris',
  'lorelei-sami',
  'lorelei-yusuf',
  'lorelei-ziyad',
  // Notionists — sketchy "Notion-style" characters (Zoish, CC0 1.0).
  'notionists-lina',
  'notionists-zaid',
  'notionists-dana',
  'notionists-rami',
  // Open Peeps — hand-drawn, diverse skin tones (Pablo Stanley, CC0 1.0).
  'openpeeps-maya',
  'openpeeps-rami',
  // Thumbs — friendly abstract characters (DiceBear, CC0 1.0).
  'thumbs-aisha',
  'thumbs-hamza',
] as const;

export const GALLERY_AVATARS: GalleryAvatar[] = GALLERY_IDS.map((id) => ({
  id,
  url: `${AVATAR_GALLERY_PATH_PREFIX}${id}.svg`,
}));

/** True when the stored value points at a gallery avatar (new path form or the
 *  legacy inline data URI from the first gallery iteration). */
export function isGalleryAvatarValue(avatarUrl: string | null | undefined): boolean {
  return (
    typeof avatarUrl === 'string' &&
    (avatarUrl.startsWith(AVATAR_GALLERY_PATH_PREFIX) || avatarUrl.startsWith('data:'))
  );
}
