#!/usr/bin/env node
/**
 * Generates the static profile avatar gallery (C-MU-UX-AVATAR-PRO).
 *
 * Build-time only — no runtime DiceBear dependency and no network calls. Run:
 *
 *   node scripts/generate-avatars.mjs
 *
 * Writes one self-contained SVG per curated entry into public/avatars-gallery/
 * (plus a README.md with attribution), where Vite copies them into dist/ and
 * the Express server also serves public/ directly. The stored avatar value is
 * the path `/avatars-gallery/<file>.svg`.
 *
 * KEEP IN SYNC — the generated filenames are whitelisted in two places:
 *   - src/components/participants/avatarChoice.ts  (GALLERY_AVATARS)
 *   - server/routes/auth.js                        (AVATAR_GALLERY_FILES)
 * If you add/rename entries here, update both lists (the script prints them).
 *
 * Determinism: DiceBear output is deterministic for a given style version +
 * seed + options, so re-running is a no-op while @dicebear/* stay on the same
 * version. A dependency bump may redraw the art; filenames (and therefore the
 * whitelists and any stored user choices) remain valid either way.
 *
 * Licensing: every style used here is CC0 1.0 (no attribution required,
 * commercial use allowed). We still embed creator credits in each file and in
 * the README as a courtesy. Verified from each style's package metadata:
 *   lorelei     — Lisa Wischofsky — CC0 1.0
 *   notionists  — Zoish           — CC0 1.0
 *   open-peeps  — Pablo Stanley   — CC0 1.0
 *   thumbs      — DiceBear        — CC0 1.0
 */
import { createAvatar } from '@dicebear/core';
import { lorelei, notionists, openPeeps, thumbs } from '@dicebear/collection';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.join(ROOT, 'public', 'avatars-gallery');

// Curated visually (seed + pastel background chosen per entry, gender- and
// look-diverse, workplace-appropriate). Backgrounds are the classic DiceBear
// pastel palette so the set reads as one family across all four styles.
const GALLERY = [
  { style: lorelei, name: 'lorelei-faris', seed: 'Faris', bg: 'd1d4f9' },
  { style: lorelei, name: 'lorelei-sami', seed: 'Sami', bg: 'ffd5dc' },
  { style: lorelei, name: 'lorelei-yusuf', seed: 'Yusuf', bg: 'd9f4dd' },
  { style: lorelei, name: 'lorelei-ziyad', seed: 'Ziyad', bg: 'ffdfbf' },
  { style: notionists, name: 'notionists-lina', seed: 'Lina', bg: 'b6e3f4' },
  { style: notionists, name: 'notionists-zaid', seed: 'Zaid', bg: 'd9f4dd' },
  { style: notionists, name: 'notionists-dana', seed: 'Dana', bg: 'ffd5dc' },
  { style: notionists, name: 'notionists-rami', seed: 'Rami', bg: 'c0aede' },
  { style: openPeeps, name: 'openpeeps-maya', seed: 'Maya', bg: 'd1d4f9' },
  { style: openPeeps, name: 'openpeeps-rami', seed: 'Rami', bg: 'ffdfbf' },
  { style: thumbs, name: 'thumbs-aisha', seed: 'Aisha', bg: 'b6e3f4' },
  { style: thumbs, name: 'thumbs-hamza', seed: 'Hamza', bg: 'ffd5dc' },
];

fs.mkdirSync(OUT_DIR, { recursive: true });

const readmeRows = [];
for (const entry of GALLERY) {
  const meta = entry.style.meta ?? {};
  const credit =
    `${meta.title ?? 'Unknown'} by ${meta.creator ?? 'Unknown'} ` +
    `(${meta.source ?? 'n/a'}) — ${meta.license?.name ?? 'unknown licence'} ` +
    `(${meta.license?.url ?? 'n/a'})`;

  const svg = createAvatar(entry.style, {
    seed: entry.seed,
    size: 96,
    backgroundColor: [entry.bg],
  })
    .toString()
    .replace(/^(<\?xml[^>]*\?>)?/, `$1<!-- ${credit}. Generated by scripts/generate-avatars.mjs -->`);

  fs.writeFileSync(path.join(OUT_DIR, `${entry.name}.svg`), svg);
  readmeRows.push(
    `| ${entry.name}.svg | ${meta.title} | ${meta.creator} | ${meta.license?.name} | ${meta.source} |`,
  );
}

fs.writeFileSync(
  path.join(OUT_DIR, 'README.md'),
  `# Avatar gallery

Static profile avatars generated at build time by \`scripts/generate-avatars.mjs\`
using [DiceBear](https://www.dicebear.com) (MIT-licensed library). Do not edit
the SVGs by hand — re-run the script instead.

All styles used are licensed **CC0 1.0** (no attribution required, commercial
use permitted); credits below are a courtesy.

| File | Style | Creator | Licence | Source |
| --- | --- | --- | --- | --- |
${readmeRows.join('\n')}
`,
);

console.log(`Wrote ${GALLERY.length} avatars + README.md to ${OUT_DIR}`);
console.log('\nWhitelist for server/routes/auth.js (AVATAR_GALLERY_FILES):');
for (const entry of GALLERY) console.log(`  '${entry.name}.svg',`);
