/**
 * In-memory WebAuthn challenge store (B-PK-2).
 *
 * Holds outstanding ceremony challenges between the options call and the
 * verify call. Keyed by the challenge string itself (base64url, generated by
 * @simplewebauthn — 32 random bytes, unguessable), mapping to the userId that
 * requested it (null for anonymous login ceremonies) and an expiry instant.
 *
 * Single-process only (Map, no shared store) — adequate for the single PM2
 * fork this app runs as, mirroring the in-memory rate limiter. Challenges are
 * single-use: consume() removes the entry before returning it, so a replayed
 * assertion can never verify twice. Stale entries are pruned lazily on store().
 */

const DEFAULT_TTL_MS = 5 * 60_000; // 5 minutes
const PRUNE_THRESHOLD = 1000;

/**
 * Factory — exported for unit tests (short TTLs, isolated state).
 * @param {{ ttlMs?: number }} [options]
 */
export function createChallengeStore({ ttlMs } = {}) {
  const ttl = ttlMs ?? DEFAULT_TTL_MS;
  /** @type {Map<string, { userId: number | null, expiresAt: number }>} */
  const challenges = new Map();

  function pruneIfLarge(now) {
    if (challenges.size < PRUNE_THRESHOLD) {
      return;
    }
    for (const [key, entry] of challenges) {
      if (now > entry.expiresAt) {
        challenges.delete(key);
      }
    }
  }

  return {
    /**
     * Registers a pending challenge.
     * @param {string} challenge base64url challenge from generate*Options
     * @param {number | null} [userId] owner of the ceremony; null for anonymous login
     */
    store(challenge, userId = null) {
      const now = Date.now();
      pruneIfLarge(now);
      challenges.set(challenge, { userId, expiresAt: now + ttl });
    },

    /**
     * Consumes a challenge (single use). Returns `{ userId }` when the
     * challenge exists and has not expired; null otherwise. The entry is
     * always removed, so a second consume of the same challenge fails.
     * @param {string} challenge
     * @returns {{ userId: number | null } | null}
     */
    consume(challenge) {
      if (typeof challenge !== 'string' || challenge.length === 0) {
        return null;
      }
      const entry = challenges.get(challenge);
      if (!entry) {
        return null;
      }
      challenges.delete(challenge);
      if (Date.now() > entry.expiresAt) {
        return null;
      }
      return { userId: entry.userId };
    },

    /** Number of pending (possibly expired, not yet pruned) challenges. */
    get size() {
      return challenges.size;
    },
  };
}

/** Process-wide singleton used by the WebAuthn routes/service. */
export const webauthnChallengeStore = createChallengeStore();
